### PR TITLE
Updated to React 0.14.3

### PR DESCRIPTION
**Pull request by ffxsam**
Feel free to lay the smack down on this PR if I did something wrong :)

### CODE REVIEW

**Comment by Jpunt** [comment]
Ah damn, seems to be that we've both did the same thing :( #146

**Comment by ffxsam** [comment]
@Jpunt Ha! That's cool, it just increases the chances of it getting merged :)

**Comment by yyx990803** [comment]
Thanks to both of you - I'll merge this one as it was submitted first, I hope you don't mind @Jpunt !

**Comment by Jpunt** [comment]
Makes sense, thanks!

**Comment by Jpunt** [comment]
@yyx990803 Can you please publish a new version to atmosphere? https://github.com/kadirahq/meteor-react-layout/pull/43 is waiting on this :)

**Pull request merged**
