### PR TITLE
Check for Mongo existence outside key checks

### PR DESCRIPTION
**Pull request by rclai**
Quick optimization.

### CODE REVIEW

**Comment by stubailo** [comment]
Thanks!

**Comment by Slava** [comment]
@stubailo is this change actually correct? I think you are checking against a server-side cursor, not the client-side one (which is LocalCollection.Cursor or something). I think the way `observe-sequence` does it, is just checking the `_publishCursor` method.

**Comment by stubailo** [comment]
Damn.

**Comment by stubailo** [comment]
@Slava wait a second. I'm pretty sure it works because I have tests for it

**Comment by Slava** [comment]
@stubailo OK, great then :)

**Pull request merged**
