### PR TITLE
add withTracker to react-meteor-data

### PR DESCRIPTION
**Pull request by dburles**
for #215

todo:

- [x] update README
- [ ] update Meteor Guide

### CODE REVIEW

**Comment by dburles** [comment]
@glasser absolutely, noted with the PR. I'll write them up shortly. The guide will also require updating.

**Comment by dburles** [comment]
@glasser @abernix please take a look at the updated readme

**Comment by dburles** [comment]
I think that should suffice

**Comment by glasser** [comment]
Released as react-meteor-data@0.2.13.  (psst @timbotnik  :) )

**Comment by dburles** [comment]
Updated guide PR: https://github.com/meteor/guide/pull/659

**Comment by timbotnik** [comment]
Sweet!! Thanks for this @dburles and @glasser - definitely a win for developer experience.

**Pull request merged**
